#!/bin/bash
# Deploy Owner Portal Netlify Fix to EC2

echo "🚀 Deploying Owner Portal Netlify Fix"
echo "======================================"
echo ""

# Backend deployment on EC2
echo "📦 STEP 1: Deploy Backend Changes to EC2"
echo ""
echo "Run these commands on your EC2 instance:"
echo ""
echo "  # SSH into EC2"
echo "  ssh -i your-key.pem ubuntu@your-ec2-ip"
echo ""
echo "  # Navigate to backend directory"
echo "  cd /path/to/fuel_finder/backend"
echo ""
echo "  # Pull latest changes (if using Git)"
echo "  git pull origin main"
echo ""
echo "  # Or upload the modified file manually:"
echo "  # scp -i your-key.pem middleware/ownerDetection.js ubuntu@your-ec2-ip:/path/to/backend/middleware/"
echo ""
echo "  # Restart PM2"
echo "  pm2 restart fuel-finder-api"
echo ""
echo "  # Check logs"
echo "  pm2 logs fuel-finder-api --lines 50"
echo ""
echo "----------------------------------------"
echo ""

# Frontend deployment
echo "📦 STEP 2: Deploy Frontend to Netlify"
echo ""
echo "Frontend is already built locally at: frontend/build/"
echo ""
echo "Option A: Using Netlify CLI"
echo "  cd frontend"
echo "  netlify deploy --prod --dir=build"
echo ""
echo "Option B: Using Git (if connected to GitHub)"
echo "  git add ."
echo "  git commit -m 'Fix owner portal subdomain detection for Netlify'"
echo "  git push origin main"
echo "  # Netlify will auto-deploy"
echo ""
echo "Option C: Manual Upload"
echo "  1. Go to https://app.netlify.com"
echo "  2. Select your site: ifuel-dangay-portal"
echo "  3. Drag & drop the 'frontend/build' folder"
echo ""
echo "----------------------------------------"
echo ""

# Testing
echo "🧪 STEP 3: Test the Fix"
echo ""
echo "1. Visit: https://ifuel-dangay-portal.netlify.app"
echo "2. Check browser console for:"
echo "   🔍 Detected Netlify owner portal: ifuel-dangay"
echo ""
echo "3. Enter API key: H8dyZF3oZx72k2EOSIjUrKeZOQ8MMmoYFr9NVv07g0I="
echo ""
echo "4. Check EC2 backend logs for:"
echo "   🏷️  Owner domain from header: ifuel-dangay"
echo "   ✅ Owner authenticated: iFuel Dangay Station"
echo ""
echo "5. Should see dashboard with station data"
echo ""
echo "----------------------------------------"
echo ""

# Files changed
echo "📝 Files Modified:"
echo ""
echo "Backend (needs EC2 deployment):"
echo "  ✅ backend/middleware/ownerDetection.js"
echo ""
echo "Frontend (built and ready):"
echo "  ✅ frontend/src/App.tsx"
echo "  ✅ frontend/src/components/owner/OwnerLogin.tsx"
echo "  ✅ frontend/src/components/owner/OwnerDashboard.tsx"
echo "  ✅ frontend/build/ (ready to deploy)"
echo ""
echo "========================================="
echo "✅ Fix Complete! Ready for deployment."
echo "========================================="
